/// <reference path="./plugin.d.ts" />
/// <reference path="./system.d.ts" />
/// <reference path="./app.d.ts" />
/// <reference path="./core.d.ts" />

/**
 * Extended Seanime arRPC bridge.
 *
 * Forwards Seanime playback (Denshi/desktop player, streams, external
 * players tracked by Seanime) to a local arRPC server -- standalone
 * `npx arrpc` / `arrpc-bun`, or the arRPC built into Equibop/Vesktop --
 * so Rich Presence shows up in custom Discord clients like Equibop.
 *
 * Why not just use Seanime's built-in Discord RPC?
 * The built-in client only tries the single IPC path
 * `$XDG_RUNTIME_DIR/discord-ipc-0`. With Flatpak clients, Docker, systemd
 * env differences, or several apps holding `discord-ipc-0`, presence
 * silently never appears. This plugin instead ships a tiny stdlib-only
 * Python helper that tries *every* transport arRPC understands:
 * WebSocket RPC on 127.0.0.1:6463-6472, then unix sockets
 * `discord-ipc-0..9` in every candidate runtime dir.
 *
 * This file is GENERATED by build.py -- edit plugin.src.ts instead.
 * The Python helper source is embedded below and written to $TEMP on load,
 * so the plugin is a single file.
 */

function init() {
    // NOTE: the $ui callback below runs in an ISOLATED runtime -- it cannot
    // read anything declared here (or at file top-level). Every constant it
    // needs (including the embedded helper) must be declared INSIDE the
    // callback body. See "Javascript restrictions" in the Seanime docs.
    $ui.register(function (ctx) {
        // Same application ID as Seanime's native presence, so artwork/buttons
        // resolve identically in Discord clients.
        var CLIENT_ID = "1224777421941899285";
        // Replaced by build.py with the JSON-escaped contents of arrpc_helper.py
        var HELPER_PY = "__ARRPC_HELPER_PY__";
        var settings = ctx.settings.define("arrpc", {
            enabled: true,
            pythonBin: "python3",
            updateIntervalSec: 15,
            showButtons: true,
            showTimestamps: true,
            // "show-paused" keeps a "Paused - ..." status visible,
            // "clear" removes presence while paused (like native behavior).
            pauseBehaviour: "show-paused",
            debug: false,
        });

        var connStatus = ctx.state("starting");
        var lastError = ctx.state("");
        var nowPlaying = ctx.state("Nothing playing");
        var lastTransport = ctx.state("");

        var lastKey = "";
        var lastSentAt = 0;
        var lastPlayingFlag = null;
        // Learned transport ("websocket" | "ipc" | "") -- parsed from the
        // helper's "OK <transport>" line to skip failing transports.
        var transportPref = "";

        function log(msg) {
            try {
                if (settings.get("debug")) console.log("[arrpc] " + msg);
            } catch (e) { /* ignore */ }
        }

        function helperPath() {
            return $filepath.join($os.tempDir(), "seanime-arrpc-helper.py");
        }

        function ensureHelper() {
            try {
                // 493 == 0o755
                $os.writeFile(helperPath(), $toBytes(HELPER_PY), 493);
                return true;
            } catch (e) {
                connStatus.set("error");
                lastError.set("cannot write helper: " + (e && e.message ? e.message : e));
                return false;
            }
        }

        function runHelper(args) {
            var bin = settings.get("pythonBin") || "python3";
            var allArgs = [helperPath()].concat(args);
            var cmd = $os.cmd.apply(null, [bin].concat(allArgs));
            var out = cmd.output();
            if (typeof out === "string") return out;
            return $toString(out);
        }

        function pushActivity(activity) {
            if (!settings.get("enabled")) return false;
            if (!ensureHelper()) return false;
            connStatus.set("sending");
            try {
                var args = ["--client-id", CLIENT_ID];
                if (transportPref) {
                    args.push("--transport", transportPref);
                }
                if (activity === null || activity === undefined) {
                    args.push("--clear");
                } else {
                    args.push("--activity", JSON.stringify(activity));
                }
                var text = runHelper(args);
                log("helper -> " + text);
                if (text.indexOf("OK websocket") === 0) {
                    transportPref = "websocket";
                    lastTransport.set(transportPref);
                    connStatus.set("ok");
                    lastError.set("");
                    return true;
                }
                if (text.indexOf("OK ipc") === 0) {
                    transportPref = "ipc";
                    lastTransport.set(transportPref);
                    connStatus.set("ok");
                    lastError.set("");
                    return true;
                }
                throw new Error(text || "empty helper output");
            } catch (e) {
                // Forget the preferred transport so the next send re-probes
                // both (the arRPC server may have restarted on new ports).
                transportPref = "";
                connStatus.set("error");
                lastError.set(String((e && e.message) || e));
                log("send failed: " + String((e && e.message) || e));
                return false;
            }
        }

        function clearPresence(reason) {
            log("clear (" + reason + ")");
            if (pushActivity(null)) {
                nowPlaying.set("Nothing playing");
            }
            lastKey = "";
            lastSentAt = 0;
            lastPlayingFlag = null;
        }

        function buildActivity(mediaId, title, image, episodeNumber, totalEpisodes, isMovie, progress, duration, paused) {
            var state;
            if (isMovie) {
                state = "Watching Movie";
            } else {
                state = "Watching Episode " + episodeNumber;
            }
            if (paused && settings.get("pauseBehaviour") === "show-paused") {
                state = "Paused - " + state;
            }
            var nowSec = Math.floor(Date.now() / 1000);
            var activity = {
                name: "Seanime",
                details: title,
                details_url: "https://anilist.co/anime/" + mediaId,
                state: state,
                assets: {
                    large_image: image,
                    large_text: title,
                    large_url: "https://anilist.co/anime/" + mediaId,
                },
                instance: true,
                type: 3,
                status_display_type: 2,
            };
            if (settings.get("showButtons")) {
                activity.buttons = [{ label: "Seanime", url: "https://seanime.app" }];
            }
            if (settings.get("showTimestamps")) {
                if (!paused && duration > 0) {
                    activity.timestamps = {
                        start: nowSec - Math.floor(progress),
                        end: nowSec + Math.floor(Math.max(0, duration - progress)),
                    };
                } else {
                    activity.timestamps = { start: nowSec };
                }
            }
            return activity;
        }

        function probe(manual) {
            if (!ensureHelper()) {
                if (manual) ctx.toast.error("arRPC: cannot write helper script");
                return;
            }
            connStatus.set("sending");
            try {
                var text = runHelper(["--client-id", CLIENT_ID, "--probe"]);
                log("probe -> " + text);
                if (text.indexOf("OK ") === 0) {
                    if (text.indexOf("OK websocket") === 0) transportPref = "websocket";
                    else if (text.indexOf("OK ipc") === 0) transportPref = "ipc";
                    lastTransport.set(transportPref);
                    connStatus.set("ok");
                    lastError.set("");
                    if (manual) ctx.toast.success("arRPC reachable (" + transportPref + ")");
                } else {
                    throw new Error(text || "probe failed");
                }
            } catch (e) {
                transportPref = "";
                connStatus.set("error");
                lastError.set(String((e && e.message) || e));
                if (manual) ctx.toast.error("arRPC not reachable. See plugin status.");
            }
        }

        ctx.playback.registerEventListener(function (ev) {
            try {
                if (!settings.get("enabled")) return;
                if (ev.isVideoStopped || ev.isVideoCompleted || ev.isStreamStopped || ev.isStreamCompleted) {
                    clearPresence("stopped");
                    return;
                }
                if (!ev.state || !ev.status) return;
                var st = ev.state;
                var so = ev.status;
                if (!st.mediaId) return;
                var key = st.mediaId + ":" + st.episodeNumber;
                var now = Date.now();
                var playing = !!so.playing;
                var intervalMs = Math.max(5, settings.get("updateIntervalSec") || 15) * 1000;
                var changed = (key !== lastKey) || (playing !== lastPlayingFlag);
                if (!changed && (now - lastSentAt) < intervalMs) return;
                if (!playing && settings.get("pauseBehaviour") === "clear") {
                    clearPresence("paused");
                    lastKey = key;
                    lastSentAt = now;
                    lastPlayingFlag = playing;
                    nowPlaying.set((st.mediaTitle || "Unknown") + " (paused, hidden)");
                    return;
                }
                var totalEp = st.mediaTotalEpisodes || 0;
                var activity = buildActivity(
                    st.mediaId,
                    st.mediaTitle || "Unknown",
                    st.mediaCoverImage || "",
                    st.episodeNumber || 0,
                    totalEp,
                    totalEp === 1,
                    so.currentTimeInSeconds || 0,
                    so.durationInSeconds || 0,
                    !playing
                );
                if (pushActivity(activity)) {
                    lastKey = key;
                    lastSentAt = now;
                    lastPlayingFlag = playing;
                    nowPlaying.set((st.mediaTitle || "Unknown") + " - Ep " + (st.episodeNumber || 0) + (playing ? "" : " (paused)"));
                }
            } catch (e) {
                console.error("[arrpc] listener error: " + String((e && e.message) || e));
            }
        });

        var tray = ctx.newTray({
            tooltipText: "arRPC bridge",
            iconUrl: "https://seanime.rahim.app/logo_2.png",
            withContent: true,
        });

        ctx.registerEventHandler("arrpc-probe", function () {
            probe(true);
        });
        ctx.registerEventHandler("arrpc-clear", function () {
            clearPresence("manual");
            ctx.toast.info("arRPC presence cleared");
        });
        ctx.registerEventHandler("arrpc-toggle", function () {
            var next = !settings.get("enabled");
            settings.set("enabled", next);
            connStatus.set(next ? "ready" : "disabled");
            if (!next) clearPresence("disabled");
            else probe(false);
            ctx.toast.info(next ? "arRPC enabled" : "arRPC disabled");
        });

        tray.render(function () {
            var statusLine = "Status: " + connStatus.get();
            if (lastTransport.get()) statusLine += " (" + lastTransport.get() + ")";
            var items = [
                tray.text("Seanime -> arRPC bridge"),
                tray.text(statusLine),
                tray.text("Now: " + nowPlaying.get()),
            ];
            if (lastError.get() && connStatus.get() === "error") {
                items.push(tray.text("Error: " + lastError.get().substring(0, 160)));
                items.push(tray.text("Enable arRPC in Equibop or run `npx arrpc`."));
            }
            items.push(tray.button(settings.get("enabled") ? "Disable" : "Enable", { onClick: "arrpc-toggle" }));
            items.push(tray.button("Test connection", { onClick: "arrpc-probe" }));
            items.push(tray.button("Clear presence", { onClick: "arrpc-clear" }));
            return tray.stack(items);
        });

        if (!settings.get("enabled")) {
            connStatus.set("disabled");
        } else {
            probe(false);
        }
    });
}
