/// <reference path="./plugin.d.ts" />
/// <reference path="./system.d.ts" />
/// <reference path="./app.d.ts" />
/// <reference path="./core.d.ts" />

/**
 * Extended Seanime arRPC bridge.
 *
 * Zero-setup Discord Rich Presence for custom clients like Equibop:
 * install, grant permissions, done -- no terminal commands. The plugin
 * spawns a small persistent companion (the embedded Python helper in
 * --daemon mode) that finds Discord/arRPC sockets itself -- including
 * Flatpak sandbox sockets (Equibop, Vesktop, ...) that Seanime's built-in
 * client never looks at -- holds ONE connection open, and applies playback
 * states to it. Presence needs a persistent connection (a fire-and-forget
 * send is cleared by the server the moment its socket closes), which is
 * exactly what the daemon provides.
 *
 * Plugin <-> daemon protocol uses two files in $TEMP:
 *   seanime-arrpc-cmd.json    {"op": "set|clear|probe|exit", "activity": {...}|null, "nonce": N}
 *   seanime-arrpc-status.json {"alive": epoch, "pid": N, "state": ..., "transport": ..., "error": ..., "activity": ...}
 *
 * This file is GENERATED by build.py -- edit plugin.src.ts instead.
 * The Python helper source is embedded below and written to $TEMP on load,
 * so the plugin is a single file.
 */

function init() {
    // NOTE: the $ui callback below runs in an ISOLATED runtime -- it cannot
    // read anything declared here (or at file top-level). Every constant it
    // needs must be declared INSIDE the callback body. See "Javascript
    // restrictions" in the Seanime docs.
    $ui.register(function (ctx) {
        // Same application ID as Seanime's native presence, so artwork
        // resolves identically in Discord clients.
        var CLIENT_ID = "1224777421941899285";
        // Replaced by build.py with the JSON-escaped contents of arrpc_helper.py
        var HELPER_PY = "__ARRPC_HELPER_PY__";

        var CMD_FILENAME = "seanime-arrpc-cmd.json";
        var STATUS_FILENAME = "seanime-arrpc-status.json";

        var settings = ctx.settings.define("arrpc", {
            enabled: true,
            pythonBin: "python3",
            updateIntervalSec: 15,
            // true: clear presence on pause/stop. false: leave last state up.
            clearOnPause: true,
            debug: false,
        });

        var connStatus = ctx.state("starting");
        var lastError = ctx.state("");
        var lastTransport = ctx.state("");
        var nowPlaying = ctx.state("Nothing playing");

        var lastKey = "";
        var lastSentAt = 0;
        var lastPlayingFlag = null;
        var cmdNonce = 0;
        var daemonStarted = false;

        function log(msg) {
            try {
                if (settings.get("debug")) console.log("[arrpc] " + msg);
            } catch (e) { /* ignore */ }
        }

        function workDir() {
            return $os.tempDir();
        }

        function helperPath() {
            return $filepath.join(workDir(), "seanime-arrpc-helper.py");
        }

        function cmdPath() {
            return $filepath.join(workDir(), CMD_FILENAME);
        }

        function statusPath() {
            return $filepath.join(workDir(), STATUS_FILENAME);
        }

        function ensureHelper() {
            try {
                // 493 == 0o755
                $os.writeFile(helperPath(), $toBytes(HELPER_PY), 493);
                return true;
            } catch (e) {
                connStatus.set("error");
                lastError.set("cannot write helper: " + (e && e.message ? e.message : e));
                return false;
            }
        }

        function ensureDaemon() {
            if (daemonStarted) return true;
            if (!ensureHelper()) return false;
            try {
                var bin = settings.get("pythonBin") || "python3";
                var acmd = $osExtra.asyncCmd(bin, helperPath(), "--daemon", "--dir", workDir(), "--client-id", CLIENT_ID);
                acmd.run(function (data, err, exitCode, signal) {
                    if (data) log("daemon: " + $toString(data));
                    if (err) log("daemon stderr: " + $toString(err));
                    if (exitCode !== undefined && exitCode !== null) {
                        log("daemon exited (" + exitCode + ")");
                        // Takeover-exits (code 0, another instance alive)
                        // keep the flag: a holder exists. Crashes re-arm.
                        if (exitCode !== 0) daemonStarted = false;
                    }
                });
                daemonStarted = true;
                log("daemon spawned");
                return true;
            } catch (e) {
                connStatus.set("error");
                lastError.set("cannot start daemon: " + (e && e.message ? e.message : e));
                return false;
            }
        }

        function sendCmd(op, activity) {
            // Teardown ops always go through (e.g. toggle-off sends "exit"
            // after flipping the switch); only new presence is gated.
            if (op === "set" && !settings.get("enabled")) return false;
            if (!ensureDaemon()) return false;
            try {
                cmdNonce++;
                var body = JSON.stringify({ op: op, activity: activity === undefined ? null : activity, nonce: cmdNonce });
                // 420 == 0o644
                $os.writeFile(cmdPath(), $toBytes(body), 420);
                return true;
            } catch (e) {
                lastError.set("cannot write command: " + (e && e.message ? e.message : e));
                connStatus.set("error");
                return false;
            }
        }

        function readStatus() {
            try {
                var raw = $toString($os.readFile(statusPath()));
                var st = JSON.parse(raw);
                if (st && typeof st === "object") return st;
                return null;
            } catch (e) {
                return null;
            }
        }

        function refreshFromStatus() {
            var st = readStatus();
            if (!st) return;
            if (st.transport) lastTransport.set(st.transport);
            if (st.state === "ok") {
                connStatus.set("ok");
                lastError.set("");
            } else if (st.state === "error") {
                connStatus.set("error");
                lastError.set(st.error || "daemon error");
            } else {
                connStatus.set(st.state || "starting");
            }
        }

        // Handshake-only probe through the daemon. Never touches display.
        function probe(manual) {
            if (!sendCmd("probe", null)) {
                if (manual) ctx.toast.error("arRPC: daemon not running");
                return;
            }
            connStatus.set("sending");
            ctx.setTimeout(function () {
                refreshFromStatus();
                var st = readStatus();
                if (manual) {
                    if (st && st.state === "ok") ctx.toast.success("arRPC reachable (" + (st.transport || "?") + ")");
                    else ctx.toast.error("arRPC not reachable. See plugin status.");
                }
            }, 3000);
        }

        function clearPresence(reason) {
            log("clear (" + reason + ")");
            sendCmd("clear", null);
            nowPlaying.set("Nothing playing");
            lastKey = "";
            lastSentAt = 0;
            lastPlayingFlag = null;
        }

        function pushPlayback(st, so, playing) {
            var key = st.mediaId + ":" + st.episodeNumber;
            var now = Date.now();
            var intervalMs = Math.max(5, settings.get("updateIntervalSec") || 15) * 1000;
            var changed = (key !== lastKey) || (playing !== lastPlayingFlag);
            if (!changed && (now - lastSentAt) < intervalMs) return;
            var progress = so.currentTimeInSeconds || 0;
            var duration = so.durationInSeconds || 0;
            var totalEp = st.mediaTotalEpisodes || 0;
            var activity = {
                name: "Seanime",
                details: st.mediaTitle || "Unknown",
                details_url: "https://anilist.co/anime/" + st.mediaId,
                state: totalEp === 1 ? "Watching Movie" : ("Watching Episode " + (st.episodeNumber || 0)),
                assets: {
                    large_image: st.mediaCoverImage || "",
                    large_text: st.mediaTitle || "Unknown",
                    large_url: "https://anilist.co/anime/" + st.mediaId,
                },
                buttons: [{ label: "Seanime", url: "https://seanime.app" }],
                instance: true,
                type: 3,
                status_display_type: 2,
            };
            if (duration > 0) {
                var nowSec = Math.floor(now / 1000);
                activity.timestamps = {
                    start: nowSec - Math.floor(progress),
                    end: nowSec + Math.floor(Math.max(0, duration - progress)),
                };
            } else {
                activity.timestamps = { start: Math.floor(now / 1000) };
            }
            if (sendCmd("set", activity)) {
                lastKey = key;
                lastSentAt = now;
                lastPlayingFlag = playing;
                nowPlaying.set((st.mediaTitle || "Unknown") + " - Ep " + (st.episodeNumber || 0) + (playing ? "" : " (paused)"));
                if (connStatus.get() !== "ok") connStatus.set("sending");
            }
        }

        ctx.playback.registerEventListener(function (ev) {
            try {
                if (!settings.get("enabled")) return;
                if (ev.isVideoStopped || ev.isVideoCompleted || ev.isStreamStopped || ev.isStreamCompleted) {
                    if (settings.get("clearOnPause")) clearPresence("stopped");
                    else {
                        lastKey = "";
                        lastSentAt = 0;
                        lastPlayingFlag = null;
                    }
                    return;
                }
                if (!ev.state || !ev.status) return;
                var st = ev.state;
                var so = ev.status;
                if (!st.mediaId) return;
                var playing = !!so.playing;
                if (!playing && settings.get("clearOnPause")) {
                    clearPresence("paused");
                    lastKey = st.mediaId + ":" + st.episodeNumber;
                    lastPlayingFlag = playing;
                    lastSentAt = Date.now();
                    return;
                }
                pushPlayback(st, so, playing);
            } catch (e) {
                console.error("[arrpc] listener error: " + String((e && e.message) || e));
            }
        });

        var tray = ctx.newTray({
            tooltipText: "arRPC bridge",
            iconUrl: "https://seanime.rahim.app/logo_2.png",
            withContent: true,
        });

        ctx.registerEventHandler("arrpc-probe", function () {
            probe(true);
        });
        ctx.registerEventHandler("arrpc-clear", function () {
            clearPresence("manual");
            ctx.toast.info("arRPC presence cleared");
        });
        ctx.registerEventHandler("arrpc-toggle", function () {
            var next = !settings.get("enabled");
            settings.set("enabled", next);
            if (!next) {
                sendCmd("exit", null);
                daemonStarted = false;
                nowPlaying.set("Nothing playing");
                connStatus.set("disabled");
            } else {
                connStatus.set("ready");
                ensureDaemon();
                probe(false);
            }
            ctx.toast.info(next ? "arRPC enabled" : "arRPC disabled");
        });

        tray.render(function () {
            // Live daemon state on every render; states trigger re-renders.
            refreshFromStatus();
            var statusLine = "Status: " + connStatus.get();
            if (lastTransport.get() && connStatus.get() === "ok") statusLine += " (" + lastTransport.get() + ")";
            var st = readStatus();
            var nowText = nowPlaying.get();
            if (st && st.activity) nowText = st.activity;
            var items = [
                tray.text("Seanime -> arRPC bridge"),
                tray.text(statusLine),
                tray.text("Now: " + nowText),
            ];
            if (lastError.get() && connStatus.get() === "error") {
                items.push(tray.text("Error: " + lastError.get().substring(0, 160)));
                items.push(tray.text("Start Equibop (or any arRPC), then Test."));
            }
            items.push(tray.button(settings.get("enabled") ? "Disable" : "Enable", { onClick: "arrpc-toggle" }));
            items.push(tray.button("Test connection", { onClick: "arrpc-probe" }));
            items.push(tray.button("Clear presence", { onClick: "arrpc-clear" }));
            return tray.stack(items);
        });

        if (!settings.get("enabled")) {
            connStatus.set("disabled");
        } else {
            ensureDaemon();
            probe(false);
        }
    });
}
// NOTE: no import/export statements -- Seanime executes the payload as a
// plain script (not a module) and Goja rejects module syntax.
